Resources:
  SensorDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SensorDataTable
      AttributeDefinitions:
        - AttributeName: sensorid
          AttributeType: S
      KeySchema:
        - AttributeName: sensorid
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  # SensorDataTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: SensorDataTable
  #     AttributeDefinitions:
  #       - AttributeName: sensorid
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: sensorid
  #         KeyType: HASH
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: 2
  #       WriteCapacityUnits: 2

# Outputs:
#   SensorDataTable:
#     Description: DynamoDB table - SensorTable
#     Value:
#       Ref:  SensorDataTable:
